# Generated by Django 4.2 on 2023-05-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='jobs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job'),
        ),
    ]
