# Generated by Django 4.2 on 2023-05-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='describe',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='name',
        ),
        migrations.RemoveField(
            model_name='email',
            name='position',
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
    ]
